### ISSUE TITLE
Fix estimates from avghr_period

### ISSUE THREAD

**Issue by sergeassaad** [sergeassaad/bme590hrm#77]
I'm having trouble dealing with the implementation for the new specifications.
I currently have a function (avghr) that takes in times, voltages, t1, and t2 where t1 and t2 are user-specified time bounds for which to return a single avghr value.

I'm trying to use the avghr function to write an avghr_period function which slides the values of t1 and t2 and spits out an average for each window by calling avghr.

All this has been done on the "avghr_period" branch, in the files "AvgHR.py" and "test_avgHR.py"

So far, I've had 2 big issues with this new feature:

1 - There seems to be an extra value at the end of the returned array which shouldn't be there
2 - The smaller the averaging period, the worse the heart rate estimate

Any help with this would be appreciated!

**Comment by mlp6** [comment]
Need more details to help debug your first point... that is way to general of a statement to make without pointing to specific lines of code that are doing the calculation and yielding the array that is too long.  Also, for the smaller averaging window, you would expect an accuracy decline if the HR varies; what do you mean by "worse"?

**Comment by sergeassaad** [comment]
Fixed the first problem!

As for the 2nd problem (dropping accuracy for smaller averaging periods), I made a dummy vector consisting of a single frequency cosine (frequency of 48bpm).

I would hope that the output is an array with values all fairly close to 48 bpm.
Am I thinking about testing in the right way?
