### ISSUE TITLE
Output for instantaneous heart rates for Cloud ECG

### ISSUE THREAD

**Issue by jac111** [sergeassaad/bme590hrm#81]
I would've asked in class, but I just thought of this question. Before I had just written my algorithm to find all the peaks and then use the peaks to calculate the instant hr. But if we want to have the output be vector the same size as t, that won't work. Can I "assign" instant hr values to all the t-values which fall within the same heartbeat? So I'm thinking if t = (0.0001, 0.0002, 0.00003), all those would have the same instant hr estimate because the dt is so small. I also attached a picture. Can the instant hr output vector have leading and trailing zeros for when times fall outside of a heartbeat?

![img_0363](https://user-images.githubusercontent.com/31519377/32251221-75300060-be66-11e7-8e93-852ba6b8f525.JPG)
![img_0364](https://user-images.githubusercontent.com/31519377/32251226-7b60ba24-be66-11e7-92df-760891fa96b0.JPG)

**Comment by mlp6** [comment]
One option would be to interpolate the HR estimates onto the prescribed time steps from the input vector.

**Comment by jac111** [comment]
So I could interpolate by assuming linear change between rates for example?
